import { suppliers, rfq } from '@/lib/demo-data'
import { currency } from '@/lib/utils'
import { BadgeCheck, CheckCircle2, Clock, FileText, ShieldCheck, TrendingDown, Truck } from 'lucide-react'

function ScoreRing({ score }: { score: number }) {
  const r = 44, circ = 2 * Math.PI * r
  const offset = circ - (score / 100) * circ
  return (
    <svg width="104" height="104" viewBox="0 0 104 104" className="shrink-0">
      <circle cx="52" cy="52" r={r} fill="none" stroke="#E2E8F0" strokeWidth="8" />
      <circle cx="52" cy="52" r={r} fill="none" stroke="#6D5DFC" strokeWidth="8"
        strokeDasharray={circ} strokeDashoffset={offset}
        strokeLinecap="round" transform="rotate(-90 52 52)" />
      <text x="52" y="48" textAnchor="middle" fontSize="26" fontWeight="800" fill="#0F172A">{score}</text>
      <text x="52" y="65" textAnchor="middle" fontSize="10" fill="#94A3B8">out of 100</text>
    </svg>
  )
}

const whyReasons = [
  { icon: TrendingDown, label: 'Lowest qualified total cost', detail: `${currency(suppliers[0].cost)} — 3.6% below next best` },
  { icon: CheckCircle2, label: 'Full material coverage', detail: `${suppliers[0].coverage}% of line items covered` },
  { icon: Truck, label: 'Meets delivery SLA', detail: `${suppliers[0].deliveryDays}-day timeline confirmed` },
  { icon: ShieldCheck, label: 'Low execution risk', detail: 'Score 21/100 — lowest across all suppliers' },
  { icon: FileText, label: 'Complete quote package', detail: `${suppliers[0].quoteCompleteness}% completeness, 2 minor gaps` },
]

export default function RecommendationsPage() {
  const best = suppliers[0]
  const rest = suppliers.slice(1)

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="text-xs font-bold uppercase tracking-[0.18em] text-accent">AI Recommendation</div>
          <h1 className="mt-1.5 text-3xl font-bold tracking-tight text-slate-900">Supplier decision — School Renovation RFO</h1>
          <p className="mt-1 text-sm text-slate-500">Generated by AI · 94% confidence · Pending approval</p>
        </div>
        <div className="flex items-center gap-2">
          <button className="rounded-xl border border-slate-200 bg-white px-5 py-2.5 text-sm font-semibold text-slate-600 shadow-sm transition hover:bg-slate-50">Request revision</button>
          <button className="flex items-center gap-2 rounded-xl bg-accent px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:opacity-90">
            <BadgeCheck size={15} /> Approve
          </button>
        </div>
      </div>

      {/* Hero recommendation card */}
      <div className="surface-hero overflow-hidden rounded-3xl">
        <div className="p-8">
          <div className="flex flex-wrap items-start gap-8">
            <ScoreRing score={best.score} />
            <div className="flex-1">
              <div className="text-[10px] font-bold uppercase tracking-[0.2em] text-accent">Recommended supplier</div>
              <h2 className="mt-2 text-5xl font-black tracking-tight text-slate-900">{best.name}</h2>
              <p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">
                Strongest risk-adjusted outcome for the School Renovation RFO. Delivers the lowest qualified cost, highest coverage, on-time delivery, and lowest execution risk of all evaluated suppliers.
              </p>
            </div>
          </div>

          {/* Stat pills */}
          <div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">
            {[
              { label: 'Potential Savings', value: currency(rfq.potentialSavings), sub: 'vs next best', highlight: true },
              { label: 'AI Confidence', value: `${rfq.confidence}%`, sub: 'High confidence', highlight: false },
              { label: 'Risk Level', value: 'Low', sub: '21 / 100 index', highlight: false },
              { label: 'Coverage', value: `${best.coverage}%`, sub: 'Line items', highlight: false },
              { label: 'Delivery', value: `${best.deliveryDays} days`, sub: 'Meets SLA', highlight: false },
            ].map((s) => (
              <div key={s.label} className={`rounded-2xl p-4 ${s.highlight ? 'bg-success/10 ring-1 ring-success/20' : 'surface'}`}>
                <div className="text-xs text-slate-500">{s.label}</div>
                <div className={`mt-2 text-2xl font-bold tracking-tight ${s.highlight ? 'text-success' : 'text-slate-900'}`}>{s.value}</div>
                <div className="mt-0.5 text-[11px] text-slate-400">{s.sub}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Two-column: Why + Alternatives */}
      <div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]">
        {/* Why BuildTech */}
        <div className="surface rounded-3xl p-6">
          <div className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">Why {best.name}?</div>
          <p className="mt-2 text-sm text-slate-500">Five factors drove the AI recommendation.</p>
          <div className="mt-5 space-y-3">
            {whyReasons.map(({ icon: Icon, label, detail }) => (
              <div key={label} className="flex items-start gap-4 rounded-2xl bg-slate-50 p-4">
                <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent">
                  <Icon size={16} />
                </div>
                <div>
                  <div className="text-sm font-semibold text-slate-800">{label}</div>
                  <div className="mt-0.5 text-xs text-slate-500">{detail}</div>
                </div>
                <CheckCircle2 size={16} className="ml-auto mt-0.5 shrink-0 text-success" />
              </div>
            ))}
          </div>
        </div>

        {/* Ranked alternatives */}
        <div className="surface rounded-3xl p-6">
          <div className="text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400">All suppliers ranked</div>
          <p className="mt-2 text-sm text-slate-500">How the other options compare.</p>

          {/* Winner */}
          <div className="mt-5 flex items-center gap-4 rounded-2xl bg-accent/[0.06] p-4 ring-1 ring-accent/20">
            <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent text-xs font-bold text-white">1</div>
            <div className="flex-1 min-w-0">
              <div className="flex items-center gap-2">
                <span className="text-sm font-bold text-slate-900">{best.name}</span>
                <span className="rounded-full bg-accent/10 px-2 py-0.5 text-[10px] font-bold text-accent">Recommended</span>
              </div>
              <div className="mt-0.5 text-xs text-slate-500">{currency(best.cost)} · {best.coverage}% coverage · {best.deliveryDays}d</div>
            </div>
            <div className="flex items-center gap-2 shrink-0">
              <div className="h-1.5 w-16 overflow-hidden rounded-full bg-accent/20">
                <div className="h-full rounded-full bg-accent" style={{ width: `${best.score}%` }} />
              </div>
              <span className="text-sm font-bold text-slate-800">{best.score}</span>
            </div>
          </div>

          {/* Alternatives */}
          <div className="mt-3 space-y-2">
            {rest.map((s, i) => (
              <div key={s.id} className="flex items-center gap-4 rounded-2xl bg-slate-50 p-4">
                <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full border border-slate-200 bg-white text-xs font-bold text-slate-500">{i + 2}</div>
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-semibold text-slate-700 truncate">{s.name}</div>
                  <div className="mt-0.5 text-xs text-slate-400">{currency(s.cost)} · {s.coverage}% · {s.deliveryDays}d</div>
                </div>
                <div className="flex items-center gap-2 shrink-0">
                  <div className="h-1.5 w-16 overflow-hidden rounded-full bg-slate-200">
                    <div className="h-full rounded-full bg-slate-400" style={{ width: `${s.score}%` }} />
                  </div>
                  <span className="text-sm font-semibold text-slate-500">{s.score}</span>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-6 rounded-2xl bg-slate-50 p-4">
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <Clock size={13} />
              Recommendation generated at 10:25 AM · Expires in 48h
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
